version: '3'
services:
    api:
      build: .
      ports:
        - "5000:5000"
      depends_on: 
        - db
    db:
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: market
      image: postgres:latest
      networks:
        - default
      ports:
        - 5405:5432
      restart: always
      volumes:
        - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: