"""empty message

Revision ID: 8457ef7f435b
Revises: 2aaecd833986
Create Date: 2021-04-14 11:04:35.153384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8457ef7f435b'
down_revision = '2aaecd833986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cardCvv', sa.String(length=3), nullable=True))
    op.add_column('users', sa.Column('cardExpirationDate', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('cardNumber', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('userPublicKey', sa.String(length=500), nullable=True))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_column('users', 'email')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'userPublicKey')
    op.drop_column('users', 'cardNumber')
    op.drop_column('users', 'cardExpirationDate')
    op.drop_column('users', 'cardCvv')
    # ### end Alembic commands ###
