"""empty message

Revision ID: 94420f81fc7d
Revises: ecd927dad9e8
Create Date: 2021-04-10 19:04:12.995841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94420f81fc7d'
down_revision = 'ecd927dad9e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_name_key', 'users', type_='unique')
    op.drop_column('users', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_name_key', 'users', ['name'])
    # ### end Alembic commands ###
