"""empty message

Revision ID: a01e07392739
Revises: f1d02ae98bd2
Create Date: 2021-04-10 18:46:54.860277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a01e07392739'
down_revision = 'f1d02ae98bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('points', sa.Float(precision=10, asdecimal=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'points')
    # ### end Alembic commands ###
